In [1]:
import pandas as pd

In [ ]:
races=pd.read_csv("../data/raw/f1db-races.csv")
races.head()

,id,year,round,date,time,grandPrixId,officialName,qualifyingFormat,sprintQualifyingFormat,circuitId,...,sprintQualifyingDate,sprintQualifyingTime,sprintRaceDate,sprintRaceTime,sprintRaceLaps,sprintRaceDistance,sprintRaceScheduledLaps,sprintRaceScheduledDistance,warmingUpDate,warmingUpTime
0,1,1950,1,1950-05-13,NaN,great-britain,1950 RAC British Grand Prix,TWO_SESSION,NaN,silverstone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1950,2,1950-05-21,NaN,monaco,Grand Prix de Monaco 1950,TWO_SESSION,NaN,monaco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1950,3,1950-05-30,NaN,indianapolis,1950 Indianapolis 500,FOUR_LAPS,NaN,indianapolis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1950,4,1950-06-04,NaN,switzerland,Grosser Preis der Schweiz 1950,TWO_SESSION,NaN,bremgarten,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,1950,5,1950-06-18,NaN,belgium,1950 Belgian Grand Prix,TWO_SESSION,NaN,spa-francorchamps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
races.shape

(1172, 47)

In [8]:
races.columns.tolist()

['id',
 'year',
 'round',
 'date',
 'time',
 'grandPrixId',
 'officialName',
 'qualifyingFormat',
 'sprintQualifyingFormat',
 'circuitId',
 'circuitLayoutId',
 'circuitType',
 'direction',
 'courseLength',
 'turns',
 'laps',
 'distance',
 'scheduledLaps',
 'scheduledDistance',
 'driversChampionshipDecider',
 'constructorsChampionshipDecider',
 'preQualifyingDate',
 'preQualifyingTime',
 'freePractice1Date',
 'freePractice1Time',
 'freePractice2Date',
 'freePractice2Time',
 'freePractice3Date',
 'freePractice3Time',
 'freePractice4Date',
 'freePractice4Time',
 'qualifying1Date',
 'qualifying1Time',
 'qualifying2Date',
 'qualifying2Time',
 'qualifyingDate',
 'qualifyingTime',
 'sprintQualifyingDate',
 'sprintQualifyingTime',
 'sprintRaceDate',
 'sprintRaceTime',
 'sprintRaceLaps',
 'sprintRaceDistance',
 'sprintRaceScheduledLaps',
 'sprintRaceScheduledDistance',
 'warmingUpDate',
 'warmingUpTime']

In [9]:
races.isnull().sum()

id                                    0
year                                  0
round                                 0
date                                  0
time                               1101
grandPrixId                           0
officialName                          0
qualifyingFormat                      0
sprintQualifyingFormat             1148
circuitId                             0
circuitLayoutId                       0
circuitType                           0
direction                             0
courseLength                          0
turns                                 0
laps                                  0
distance                              0
scheduledLaps                      1088
scheduledDistance                  1088
driversChampionshipDecider            0
constructorsChampionshipDecider       0
preQualifyingDate                  1172
preQualifyingTime                  1172
freePractice1Date                  1101
freePractice1Time                  1101
freePractice2Date                  1119
freePractice2Time                  1119
freePractice3Date                  1119
freePractice3Time                  1119
freePractice4Date                  1172
freePractice4Time                  1172
qualifying1Date                    1172
qualifying1Time                    1172
qualifying2Date                    1172
qualifying2Time                    1172
qualifyingDate                     1101
qualifyingTime                     1101
sprintQualifyingDate               1154
sprintQualifyingTime               1154
sprintRaceDate                     1154
sprintRaceTime                     1154
sprintRaceLaps                     1142
sprintRaceDistance                 1142
sprintRaceScheduledLaps            1168
sprintRaceScheduledDistance        1168
warmingUpDate                      1172
warmingUpTime                      1172
dtype: int64

In [12]:
races_2022_2025=races[races["year"].between(2022, 2025)].copy()
races_2022_2025

,id,year,round,date,time,grandPrixId,officialName,qualifyingFormat,sprintQualifyingFormat,circuitId,...,sprintQualifyingDate,sprintQualifyingTime,sprintRaceDate,sprintRaceTime,sprintRaceLaps,sprintRaceDistance,sprintRaceScheduledLaps,sprintRaceScheduledDistance,warmingUpDate,warmingUpTime
1057,1058,2022,1,2022-03-20,NaN,bahrain,Formula 1 Gulf Air Bahrain Grand Prix 2022,KNOCKOUT,NaN,bahrain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1058,1059,2022,2,2022-03-27,NaN,saudi-arabia,Formula 1 stc Saudi Arabian Grand Prix 2022,KNOCKOUT,NaN,jeddah,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1059,1060,2022,3,2022-04-10,NaN,australia,Formula 1 Heineken Australian Grand Prix 2022,KNOCKOUT,NaN,melbourne,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1060,1061,2022,4,2022-04-24,NaN,emilia-romagna,Formula 1 Rolex Gran Premio dell'Emilia Romagn...,SPRINT_RACE,NaN,imola,...,NaN,NaN,NaN,NaN,21.0,102.871,NaN,NaN,NaN,NaN
1061,1062,2022,5,2022-05-08,NaN,miami,Formula 1 Crypto.com Miami Grand Prix 2022,KNOCKOUT,NaN,miami,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1144,1145,2025,20,2025-10-26,20:00,mexico,Formula 1 Gran Premio de la Ciudad de México 2025,KNOCKOUT,NaN,mexico-city,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1145,1146,2025,21,2025-11-09,17:00,sao-paulo,Formula 1 MSC Cruises Grande Prêmio de São Pau...,KNOCKOUT,SPRINT_SHOOTOUT,interlagos,...,2025-11-07,18:30,2025-11-08,14:00,24.0,103.356,NaN,NaN,NaN,NaN
1146,1147,2025,22,2025-11-23,04:00,las-vegas,Formula 1 Heineken Las Vegas Grand Prix 2025,KNOCKOUT,NaN,las-vegas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1147,1148,2025,23,2025-11-30,16:00,qatar,Formula 1 Qatar Airways Qatar Grand Prix 2025,KNOCKOUT,SPRINT_SHOOTOUT,lusail,...,2025-11-28,17:30,2025-11-29,14:00,19.0,102.689,NaN,NaN,NaN,NaN
1148,1149,2025,24,2025-12-07,13:00,abu-dhabi,Formula 1 Etihad Airways Abu Dhabi Grand Prix ...,KNOCKOUT,NaN,yas-marina,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
races_2022_2025.groupby("year").size()

year
2022    22
2023    22
2024    24
2025    24
dtype: int64

In [18]:
results = pd.read_csv("../data/raw/f1db-races-race-results.csv")

C:\Users\LEGION\AppData\Local\Temp\ipykernel_21308\712806.py:1: DtypeWarning: Columns (0: fastestLap, 1: driverOfTheDay) have mixed types. Specify dtype option on import or set low_memory=False.
  results = pd.read_csv("../data/raw/f1db-races-race-results.csv")

In [20]:
results.head()

,raceId,year,round,positionDisplayOrder,positionNumber,positionText,driverNumber,driverId,constructorId,engineManufacturerId,...,polePosition,qualificationPositionNumber,qualificationPositionText,gridPositionNumber,gridPositionText,positionsGained,pitStops,fastestLap,driverOfTheDay,grandSlam
0,1,1950,1,1,1.0,1,2,nino-farina,alfa-romeo,alfa-romeo,...,True,1.0,1,1.0,1,0.0,NaN,True,NaN,False
1,1,1950,1,2,2.0,2,3,luigi-fagioli,alfa-romeo,alfa-romeo,...,False,2.0,2,2.0,2,0.0,NaN,False,NaN,False
2,1,1950,1,3,3.0,3,4,reg-parnell,alfa-romeo,alfa-romeo,...,False,4.0,4,4.0,4,1.0,NaN,False,NaN,False
3,1,1950,1,4,4.0,4,14,yves-giraud-cabantous,talbot-lago,talbot-lago,...,False,6.0,6,6.0,6,2.0,NaN,False,NaN,False
4,1,1950,1,5,5.0,5,15,louis-rosier,talbot-lago,talbot-lago,...,False,9.0,9,9.0,9,4.0,NaN,False,NaN,False

In [22]:
qualifying = pd.read_csv("../data/raw/f1db-races-qualifying-results.csv")
qualifying.head()

,raceId,year,round,positionDisplayOrder,positionNumber,positionText,driverNumber,driverId,constructorId,engineManufacturerId,...,q1Millis,q2,q2Millis,q3,q3Millis,gap,gapMillis,interval,intervalMillis,laps
0,1,1950,1,1,1.0,1,2,nino-farina,alfa-romeo,alfa-romeo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1950,1,2,2.0,2,3,luigi-fagioli,alfa-romeo,alfa-romeo,...,NaN,NaN,NaN,NaN,NaN,+0.200,200.0,+0.200,200.0,NaN
2,1,1950,1,3,3.0,3,1,juan-manuel-fangio,alfa-romeo,alfa-romeo,...,NaN,NaN,NaN,NaN,NaN,+0.200,200.0,+0.000,0.0,NaN
3,1,1950,1,4,4.0,4,4,reg-parnell,alfa-romeo,alfa-romeo,...,NaN,NaN,NaN,NaN,NaN,+1.400,1400.0,+1.200,1200.0,NaN
4,1,1950,1,5,5.0,5,21,birabongse-bhanudej,maserati,maserati,...,NaN,NaN,NaN,NaN,NaN,+1.800,1800.0,+0.400,400.0,NaN

In [23]:
grid = pd.read_csv("../data/raw/f1db-races-starting-grid-positions.csv")
grid.head()

,raceId,year,round,positionDisplayOrder,positionNumber,positionText,driverNumber,driverId,constructorId,engineManufacturerId,tyreManufacturerId,qualificationPositionNumber,qualificationPositionText,gridPenalty,gridPenaltyPositions,time,timeMillis
0,1,1950,1,1,1.0,1,2,nino-farina,alfa-romeo,alfa-romeo,pirelli,1.0,1,NaN,NaN,1:50.800,110800.0
1,1,1950,1,2,2.0,2,3,luigi-fagioli,alfa-romeo,alfa-romeo,pirelli,2.0,2,NaN,NaN,1:51.000,111000.0
2,1,1950,1,3,3.0,3,1,juan-manuel-fangio,alfa-romeo,alfa-romeo,pirelli,3.0,3,NaN,NaN,1:51.000,111000.0
3,1,1950,1,4,4.0,4,4,reg-parnell,alfa-romeo,alfa-romeo,pirelli,4.0,4,NaN,NaN,1:52.200,112200.0
4,1,1950,1,5,5.0,5,21,birabongse-bhanudej,maserati,maserati,pirelli,5.0,5,NaN,NaN,1:52.600,112600.0

In [27]:
results.columns.tolist()

['raceId',
 'year',
 'round',
 'positionDisplayOrder',
 'positionNumber',
 'positionText',
 'driverNumber',
 'driverId',
 'constructorId',
 'engineManufacturerId',
 'tyreManufacturerId',
 'sharedCar',
 'laps',
 'time',
 'timeMillis',
 'timePenalty',
 'timePenaltyMillis',
 'gap',
 'gapMillis',
 'gapLaps',
 'interval',
 'intervalMillis',
 'reasonRetired',
 'points',
 'polePosition',
 'qualificationPositionNumber',
 'qualificationPositionText',
 'gridPositionNumber',
 'gridPositionText',
 'positionsGained',
 'pitStops',
 'fastestLap',
 'driverOfTheDay',
 'grandSlam']

In [28]:
qualifying.columns.tolist()

['raceId',
 'year',
 'round',
 'positionDisplayOrder',
 'positionNumber',
 'positionText',
 'driverNumber',
 'driverId',
 'constructorId',
 'engineManufacturerId',
 'tyreManufacturerId',
 'time',
 'timeMillis',
 'q1',
 'q1Millis',
 'q2',
 'q2Millis',
 'q3',
 'q3Millis',
 'gap',
 'gapMillis',
 'interval',
 'intervalMillis',
 'laps']

In [29]:
grid.columns.tolist()

['raceId',
 'year',
 'round',
 'positionDisplayOrder',
 'positionNumber',
 'positionText',
 'driverNumber',
 'driverId',
 'constructorId',
 'engineManufacturerId',
 'tyreManufacturerId',
 'qualificationPositionNumber',
 'qualificationPositionText',
 'gridPenalty',
 'gridPenaltyPositions',
 'time',
 'timeMillis']

In [30]:
results_df = results[
    ["raceId", "driverId", "positionNumber"]
].rename(columns={"positionNumber": "finish_position"})

In [31]:
qualifying_df = qualifying[
    ["raceId", "driverId", "positionNumber"]
].rename(columns={"positionNumber": "qualifying_position"})

In [32]:
grid_df = grid[
    ["raceId", "driverId", "positionNumber"]
].rename(columns={"positionNumber": "grid_position"})

In [33]:
for name, df in[
    ("Results",results_df),
    ("Qualifying",qualifying_df),
    ("Grid",grid_df)]:
    print(name, df.duplicated(["raceId","driverId"]).sum())

Results 95
Qualifying 1
Grid 0

In [42]:
results_df[
    results_df.duplicated(
        ["raceId", "driverId"],
        keep=False
    )
].sort_values(["raceId", "driverId"])

      raceId           driverId  finish_position
70         3    fred-agabashian             25.0
74         3    fred-agabashian             28.0
49         3  tony-bettenhausen              5.0
77         3  tony-bettenhausen             31.0
117        6     eugene-chaboud              5.0
...      ...                ...              ...
3060     130        mike-spence              NaN
6415     274     rolf-stommelen              6.0
6436     274     rolf-stommelen              NaN
7491     311        harald-ertl              NaN
7494     311        harald-ertl              NaN

[184 rows x 3 columns]

In [47]:
qualifying_df[
    qualifying_df.duplicated(
        ["raceId", "driverId"],
          keep=False
    )
]

       raceId         driverId  qualifying_position
25511    1089  valtteri-bottas                  NaN
25517    1089  valtteri-bottas                  NaN

In [ ]:
recent_results= results_df[
    results_df["raceId"].isin(races_2022_2025["id"])
]
recent_qualifying = qualifying_df[
    qualifying_df["raceId"].isin(races_2022_2025["id"])]
print(
    "Results:",
    recent_results.duplicated(["raceId", "driverId"]).sum())
print(
    "Qualifying:",
    recent_qualifying.duplicated(["raceId", "driverId"]).sum())

Results: 0
Qualifying: 1

In [52]:
recent_qualifying= recent_qualifying.drop_duplicates(
    subset=["raceId", "driverId"]
)
recent_qualifying.duplicated(
    ["raceId", "driverId"]
).sum()

np.int64(0)

In [53]:
race_data= recent_results.merge(
    recent_qualifying,
    on=["raceId","driverId"],
    how="left",
    validate="one_to_one"

)

In [55]:
race_data

      raceId          driverId  finish_position  qualifying_position
0       1058   charles-leclerc              1.0                  1.0
1       1058   carlos-sainz-jr              2.0                  3.0
2       1058    lewis-hamilton              3.0                  5.0
3       1058    george-russell              4.0                  9.0
4       1058   kevin-magnussen              5.0                  7.0
...      ...               ...              ...                  ...
1834    1149   alexander-albon             16.0                 17.0
1835    1149      isack-hadjar             17.0                  9.0
1836    1149       liam-lawson             18.0                 13.0
1837    1149      pierre-gasly             19.0                 19.0
1838    1149  franco-colapinto             20.0                 20.0

[1839 rows x 4 columns]

In [60]:
print(race_data.shape)
display(race_data.head())
print(race_data.isnull().sum())

(1839, 4)

   raceId         driverId  finish_position  qualifying_position
0    1058  charles-leclerc              1.0                  1.0
1    1058  carlos-sainz-jr              2.0                  3.0
2    1058   lewis-hamilton              3.0                  5.0
3    1058   george-russell              4.0                  9.0
4    1058  kevin-magnussen              5.0                  7.0

raceId                   0
driverId                 0
finish_position        220
qualifying_position     27
dtype: int64

In [65]:
print("Original rows:", len(recent_results))
print("Merged rows:", len(race_data))

print(
    "Duplicates:",
    race_data.duplicated(["raceId", "driverId"]).sum()
)

Original rows: 1839
Merged rows: 1839
Duplicates: 0

In [66]:
grid_recent= grid_df[
    grid_df["raceId"].isin(races_2022_2025["id"])
]

race_data = race_data.merge(
    grid_recent,
    on=["raceId", "driverId"],
    how="left",
    validate="one_to_one"
)

In [67]:
race_data.head()

,raceId,driverId,finish_position,qualifying_position,grid_position
0,1058,charles-leclerc,1.0,1.0,1.0
1,1058,carlos-sainz-jr,2.0,3.0,3.0
2,1058,lewis-hamilton,3.0,5.0,5.0
3,1058,george-russell,4.0,9.0,9.0
4,1058,kevin-magnussen,5.0,7.0,7.0

In [69]:
race_data.shape

(1839, 5)

In [70]:
race_data.isnull().sum()

raceId                   0
driverId                 0
finish_position        220
qualifying_position     27
grid_position           65
dtype: int64

In [71]:
missing_finish = results[
    (results["year"].between(2022, 2025)) &
    (results["positionNumber"].isna())
]

missing_finish[
    ["year", "round", "driverId", "positionText", "reasonRetired"]
]

       year  round          driverId positionText            reasonRetired
25471  2022      1      pierre-gasly          DNF               Power unit
25486  2022      2   valtteri-bottas          DNF           Cooling system
25487  2022      2   fernando-alonso          DNF           Water pressure
25488  2022      2  daniel-ricciardo          DNF                  Gearbox
25489  2022      2   nicholas-latifi          DNF                 Accident
...     ...    ...               ...          ...                      ...
27248  2025     22      lance-stroll          DNF                Collision
27249  2025     22      lando-norris          DSQ  Illegal skid block wear
27250  2025     22     oscar-piastri          DSQ  Illegal skid block wear
27269  2025     23    oliver-bearman          DNF           Pit stop issue
27270  2025     23   nico-hulkenberg          DNF                Collision

[220 rows x 5 columns]

In [72]:
missing_finish["positionText"].value_counts(dropna=False)

positionText
DNF    197
DNS     13
DSQ     10
Name: count, dtype: int64

In [73]:
missing_finish["reasonRetired"].value_counts(dropna=False)

reasonRetired
Collision                      38
Collision damage               34
Accident                       27
Engine                         21
Hydraulics                     10
Gearbox                         8
Undertray                       8
Brakes                          7
Power unit                      6
Illegal skid block wear         6
Overheating                     5
Spun off                        4
Water pressure                  3
Suspension                      3
Water leak                      3
Oil leak                        3
Withdrew                        3
Car underweight                 3
Accident in qualifying          2
Fuel leak                       2
Turbo                           2
Accident damage                 2
Cooling system                  1
Power loss                      1
Mechanical                      1
Fuel pump                       1
Differential                    1
Electrical                      1
Steering                        1
Rear wing                       1
Unwell                          1
Car damaged in qualifying       1
Received outside assistance     1
Clutch                          1
Accident on formation lap       1
Fuel system                     1
Throttle                        1
Oil pressure                    1
Injury                          1
Transmission                    1
Handling                        1
Pit stop issue                  1
Name: count, dtype: int64

In [74]:
race_data[race_data["qualifying_position"].isna()].head(20)

,raceId,driverId,finish_position,qualifying_position,grid_position
38,1059,yuki-tsunoda,NaN,NaN,19.0
49,1060,alexander-albon,10.0,NaN,20.0
51,1060,lance-stroll,12.0,NaN,19.0
70,1061,alexander-albon,11.0,NaN,18.0
87,1062,esteban-ocon,8.0,NaN,20.0
475,1081,logan-sargeant,16.0,NaN,20.0
484,1082,sergio-perez,5.0,NaN,NaN
519,1083,nyck-de-vries,NaN,NaN,18.0
631,1089,valtteri-bottas,12.0,NaN,20.0
756,1095,logan-sargeant,NaN,NaN,NaN
815,1098,logan-sargeant,16.0,NaN,19.0
875,1101,logan-sargeant,16.0,NaN,20.0
917,1103,guanyu-zhou,18.0,NaN,20.0
1015,1108,logan-sargeant,17.0,NaN,19.0
1037,1109,nico-hulkenberg,NaN,NaN,19.0
1038,1109,kevin-magnussen,NaN,NaN,20.0
1172,1116,alexander-albon,14.0,NaN,19.0
1174,1116,logan-sargeant,16.0,NaN,18.0
1210,1118,pierre-gasly,12.0,NaN,18.0
1372,1126,oliver-bearman,14.0,NaN,NaN

In [75]:
race_data.dtypes

raceId                   int64
driverId                   str
finish_position        float64
qualifying_position    float64
grid_position          float64
dtype: object

In [76]:
race_data[
    race_data["qualifying_position"].isna()
]["grid_position"].value_counts(dropna=False)

grid_position
20.0    9
19.0    7
18.0    6
NaN     5
Name: count, dtype: int64

In [77]:
race_data[
    race_data["qualifying_position"].isna() &
    race_data["grid_position"].isna()
]

,raceId,driverId,finish_position,qualifying_position,grid_position
484,1082,sergio-perez,5.0,NaN,NaN
756,1095,logan-sargeant,NaN,NaN,NaN
1372,1126,oliver-bearman,14.0,NaN,NaN
1488,1132,yuki-tsunoda,10.0,NaN,NaN
1712,1143,alexander-albon,14.0,NaN,NaN

In [78]:
race_data[
    race_data[
        ["finish_position", "qualifying_position", "grid_position"]
    ].isna().any(axis=1)
]

,raceId,driverId,finish_position,qualifying_position,grid_position
19,1058,pierre-gasly,NaN,10.0,10.0
34,1059,valtteri-bottas,NaN,8.0,8.0
35,1059,fernando-alonso,NaN,7.0,7.0
36,1059,daniel-ricciardo,NaN,12.0,14.0
37,1059,nicholas-latifi,NaN,19.0,18.0
...,...,...,...,...,...
1797,1147,lando-norris,NaN,1.0,1.0
1798,1147,oscar-piastri,NaN,5.0,5.0
1812,1148,franco-colapinto,14.0,20.0,NaN
1817,1148,oliver-bearman,NaN,13.0,13.0
1818,1148,nico-hulkenberg,NaN,11.0,11.0

In [80]:
race_data[race_data["grid_position"].isna()]["finish_position"].isna().value_counts()

finish_position
False    56
True      9
Name: count, dtype: int64

In [81]:
missing_grid = race_data[
    race_data["grid_position"].isna()
]

missing_grid[
    missing_grid["finish_position"].notna()
].head(20)

,raceId,driverId,finish_position,qualifying_position,grid_position
74,1061,guanyu-zhou,15.0,14.0,NaN
210,1068,valtteri-bottas,11.0,12.0,NaN
268,1071,pierre-gasly,9.0,12.0,NaN
357,1075,pierre-gasly,18.0,17.0,NaN
370,1076,esteban-ocon,11.0,18.0,NaN
416,1078,yuki-tsunoda,17.0,19.0,NaN
484,1082,sergio-perez,5.0,NaN,NaN
490,1082,valtteri-bottas,11.0,19.0,NaN
514,1083,esteban-ocon,15.0,12.0,NaN
516,1083,nico-hulkenberg,17.0,17.0,NaN
570,1086,charles-leclerc,11.0,19.0,NaN
579,1086,logan-sargeant,20.0,20.0,NaN
616,1088,nyck-de-vries,17.0,20.0,NaN
617,1088,kevin-magnussen,18.0,19.0,NaN
677,1091,nico-hulkenberg,18.0,20.0,NaN
695,1092,kevin-magnussen,16.0,18.0,NaN
731,1094,guanyu-zhou,12.0,19.0,NaN
769,1096,sergio-perez,10.0,13.0,NaN
786,1097,lance-stroll,7.0,19.0,NaN
790,1097,nico-hulkenberg,11.0,16.0,NaN

In [85]:
grid[
    (grid["raceId"] == 1061) &
    (grid["driverId"] == "guanyu-zhou")
]

,raceId,year,round,positionDisplayOrder,positionNumber,positionText,driverNumber,driverId,constructorId,engineManufacturerId,tyreManufacturerId,qualificationPositionNumber,qualificationPositionText,gridPenalty,gridPenaltyPositions,time,timeMillis
23769,1061,2022,4,20,NaN,PL,24,guanyu-zhou,alfa-romeo,ferrari,pirelli,NaN,DNF,NaN,NaN,NaN,NaN

In [86]:
grid[
    grid["positionNumber"].isna()
]["positionText"].value_counts(dropna=False)

positionText
PL    161
Name: count, dtype: int64

In [87]:
grid_df["pit_lane_start"] = (
    grid["positionText"].eq("PL").astype(int)
)

In [88]:
pit_lane = grid[
    ["raceId", "driverId", "positionText"]
].copy()

pit_lane["pit_lane_start"] = (
    pit_lane["positionText"] == "PL"
).astype(int)

pit_lane = pit_lane.drop(columns="positionText")

pit_lane.head()

   raceId             driverId  pit_lane_start
0       1          nino-farina               0
1       1        luigi-fagioli               0
2       1   juan-manuel-fangio               0
3       1          reg-parnell               0
4       1  birabongse-bhanudej               0

In [93]:
race_data = race_data.merge(
    pit_lane,
    on=["raceId", "driverId"],
    how="left",
    validate="one_to_one"
)

MergeError: Passing 'suffixes' which cause duplicate columns {'pit_lane_start_y', 'pit_lane_start_x'} is not allowed.

In [94]:
race_data.shape

(1839, 8)

In [95]:
race_data.columns.tolist()

['raceId',
 'driverId',
 'finish_position',
 'qualifying_position',
 'grid_position',
 'pit_lane_start_x',
 'pit_lane_start_y',
 'pit_lane_start']

In [96]:
race_data[
    ["pit_lane_start_x", "pit_lane_start_y", "pit_lane_start"]
].head(10)

   pit_lane_start_x  pit_lane_start_y  pit_lane_start
0               0.0               0.0             0.0
1               0.0               0.0             0.0
2               0.0               0.0             0.0
3               0.0               0.0             0.0
4               0.0               0.0             0.0
5               0.0               0.0             0.0
6               0.0               0.0             0.0
7               0.0               0.0             0.0
8               0.0               0.0             0.0
9               0.0               0.0             0.0

In [97]:
race_data = race_data.drop(
    columns=["pit_lane_start_x", "pit_lane_start_y"]
)

In [98]:
race_data.shape

(1839, 6)

In [99]:
race_data["pit_lane_start"].value_counts(dropna=False)

pit_lane_start
0.0    1774
1.0      63
NaN       2
Name: count, dtype: int64

In [100]:
race_data.duplicated(["raceId", "driverId"]).sum()

np.int64(0)

In [101]:
race_data[
    race_data["pit_lane_start"].isna()
]

,raceId,driverId,finish_position,qualifying_position,grid_position,pit_lane_start
39,1059,mick-schumacher,NaN,14.0,NaN,NaN
739,1094,lance-stroll,NaN,20.0,NaN,NaN

In [102]:
race_data.isnull().sum()

raceId                   0
driverId                 0
finish_position        220
qualifying_position     27
grid_position           65
pit_lane_start           2
dtype: int64

In [103]:
race_data["has_finish_position"] = (
    race_data["finish_position"].notna().astype(int)
)

race_data["has_finish_position"].value_counts()

has_finish_position
1    1619
0     220
Name: count, dtype: int64

In [104]:
results[
    (results["year"].between(2022, 2025)) &
    (results["positionNumber"].isna())
]["positionText"].value_counts()

positionText
DNF    197
DNS     13
DSQ     10
Name: count, dtype: int64

In [107]:
results[
    (results["year"].between(2022, 2025)) &
    (results["positionNumber"].isna())
]["positionText"].value_counts()

positionText
DNF    197
DNS     13
DSQ     10
Name: count, dtype: int64

In [108]:
race_status = results[
    ["raceId", "driverId", "positionText"]
].drop_duplicates(subset=["raceId", "driverId"])

race_data = race_data.merge(
    race_status,
    on=["raceId", "driverId"],
    how="left",
    validate="one_to_one"
)

race_data.head()

,raceId,driverId,finish_position,qualifying_position,grid_position,pit_lane_start,has_finish_position,positionText_x,positionText_y
0,1058,charles-leclerc,1.0,1.0,1.0,0.0,1,1,1
1,1058,carlos-sainz-jr,2.0,3.0,3.0,0.0,1,2,2
2,1058,lewis-hamilton,3.0,5.0,5.0,0.0,1,3,3
3,1058,george-russell,4.0,9.0,9.0,0.0,1,4,4
4,1058,kevin-magnussen,5.0,7.0,7.0,0.0,1,5,5

In [111]:
race_data = race_data.drop(columns=["positionText_y"])

race_data = race_data.rename(
    columns={"positionText_x": "positionText"}
)

race_data.head()

,raceId,driverId,finish_position,qualifying_position,grid_position,pit_lane_start,has_finish_position,positionText
0,1058,charles-leclerc,1.0,1.0,1.0,0.0,1,1
1,1058,carlos-sainz-jr,2.0,3.0,3.0,0.0,1,2
2,1058,lewis-hamilton,3.0,5.0,5.0,0.0,1,3
3,1058,george-russell,4.0,9.0,9.0,0.0,1,4
4,1058,kevin-magnussen,5.0,7.0,7.0,0.0,1,5

In [112]:
race_data.shape

(1839, 8)

In [113]:
race_data[
    race_data["finish_position"].isna()
]["positionText"].value_counts(dropna=False)

positionText
DNF    197
DNS     13
DSQ     10
Name: count, dtype: int64

In [114]:
race_data.loc[
    race_data["pit_lane_start"].isna(),
    ["raceId", "driverId", "positionText"]
]

     raceId         driverId positionText
39     1059  mick-schumacher          DNS
739    1094     lance-stroll          DNS

In [115]:
race_data["pit_lane_start"] = (
    race_data["pit_lane_start"].fillna(0).astype(int)
)

race_data.isnull().sum()

raceId                   0
driverId                 0
finish_position        220
qualifying_position     27
grid_position           65
pit_lane_start           0
has_finish_position      0
positionText             0
dtype: int64

In [116]:
race_data.loc[
    race_data["qualifying_position"].isna(),
    ["raceId", "driverId", "finish_position", "grid_position",
     "pit_lane_start", "positionText"]
]

,raceId,driverId,finish_position,grid_position,pit_lane_start,positionText
38,1059,yuki-tsunoda,NaN,19.0,0,DNS
49,1060,alexander-albon,10.0,20.0,0,10
51,1060,lance-stroll,12.0,19.0,0,12
70,1061,alexander-albon,11.0,18.0,0,11
87,1062,esteban-ocon,8.0,20.0,0,8
475,1081,logan-sargeant,16.0,20.0,0,16
484,1082,sergio-perez,5.0,NaN,1,5
519,1083,nyck-de-vries,NaN,18.0,0,DNF
631,1089,valtteri-bottas,12.0,20.0,0,12
756,1095,logan-sargeant,NaN,NaN,1,DNF
815,1098,logan-sargeant,16.0,19.0,0,16
875,1101,logan-sargeant,16.0,20.0,0,16
917,1103,guanyu-zhou,18.0,20.0,0,18
1015,1108,logan-sargeant,17.0,19.0,0,17
1037,1109,nico-hulkenberg,NaN,19.0,0,DNF
1038,1109,kevin-magnussen,NaN,20.0,0,DNF
1172,1116,alexander-albon,14.0,19.0,0,14
1174,1116,logan-sargeant,16.0,18.0,0,16
1210,1118,pierre-gasly,12.0,18.0,0,12
1372,1126,oliver-bearman,14.0,NaN,1,14
1488,1132,yuki-tsunoda,10.0,NaN,1,10
1645,1140,lance-stroll,7.0,19.0,0,7
1692,1142,esteban-ocon,14.0,20.0,0,14
1708,1143,carlos-sainz-jr,10.0,18.0,0,10
1712,1143,alexander-albon,14.0,NaN,1,14
1734,1144,isack-hadjar,16.0,20.0,0,16
1778,1146,gabriel-bortoleto,NaN,18.0,0,DNF

In [118]:
race_data[
    race_data["qualifying_position"].isna()
][["grid_position", "pit_lane_start", "positionText"]].value_counts(
    dropna=False
)

grid_position  pit_lane_start  positionText
20.0           0               16              3
18.0           0               DNF             2
NaN            1               14              2
19.0           0               DNS             1
20.0           0               10              1
19.0           0               12              1
18.0           0               11              1
20.0           0               8               1
NaN            1               5               1
20.0           0               12              1
NaN            1               DNF             1
19.0           0               16              1
20.0           0               18              1
19.0           0               17              1
                               DNF             1
20.0           0               DNF             1
19.0           0               14              1
18.0           0               16              1
                               12              1
NaN            1               10              1
19.0           0               7               1
20.0           0               14              1
18.0           0               10              1
Name: count, dtype: int64

In [119]:
results[
    (results["year"].between(2022, 2025)) &
    (results["positionNumber"].isna())
][["year", "raceId", "driverId", "positionText"]].sort_values(
    ["year", "raceId"]
)

       year  raceId          driverId positionText
25471  2022    1058      pierre-gasly          DNF
25486  2022    1059   valtteri-bottas          DNF
25487  2022    1059   fernando-alonso          DNF
25488  2022    1059  daniel-ricciardo          DNF
25489  2022    1059   nicholas-latifi          DNF
...     ...     ...               ...          ...
27248  2025    1147      lance-stroll          DNF
27249  2025    1147      lando-norris          DSQ
27250  2025    1147     oscar-piastri          DSQ
27269  2025    1148    oliver-bearman          DNF
27270  2025    1148   nico-hulkenberg          DNF

[220 rows x 4 columns]

In [124]:
race_data[
    race_data["grid_position"].isna()
][
    [
        "raceId",
        "driverId",
        "qualifying_position",
        "pit_lane_start",
        "positionText"
    ]
]

,raceId,driverId,qualifying_position,pit_lane_start,positionText
39,1059,mick-schumacher,14.0,0,DNS
74,1061,guanyu-zhou,14.0,1,15
210,1068,valtteri-bottas,12.0,1,11
268,1071,pierre-gasly,12.0,1,9
357,1075,pierre-gasly,17.0,1,18
...,...,...,...,...,...
1717,1143,pierre-gasly,18.0,1,19
1761,1146,max-verstappen,16.0,1,3
1770,1146,esteban-ocon,17.0,1,12
1790,1147,yuki-tsunoda,19.0,1,12
1812,1148,franco-colapinto,20.0,1,14

In [125]:
pd.crosstab(
    race_data.loc[race_data["grid_position"].isna(), "pit_lane_start"],
    race_data.loc[race_data["grid_position"].isna(), "positionText"]
)

positionText,10,11,12,13,14,15,16,17,18,19,20,3,5,6,7,9,DNF,DNS
pit_lane_start,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2
1,3,5,4,4,5,6,3,9,6,2,1,1,1,2,2,2,6,1

In [129]:
race_data.to_csv("../data/processed/race_data.csv", index=False)